version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    env_file:
      - .env

  db:
    container_name: django_endpoint_db
    image: mariadb:10.11
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

  cache:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"