version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - redis
      - db
    networks:
      - local_network

  db:
    image: mariadb:10.11
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - local_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: REDIS_PASSWORD
    env_file:
      - .env
    command: redis-server --requirepass pass1
    networks:
      - local_network

networks:
  local_network:
    name: api-network